In [1]:
import pandas as pd
import os

In [7]:
sales = pd.read_excel("sales_data.xlsx")

In [9]:
sales.shape

(3791, 6)

In [10]:
sales.head()

,Sales Person,Geography,Product,Date,Amount,Boxes
0,Barr Faughny,New Zealand,Raspberry Choco,2021-01-01,8414,495
1,Dennison Crosswaite,Canada,White Choc,2021-01-01,532,54
2,Karlen McCaffrey,USA,99% Dark & Pure,2021-01-01,5376,269
3,Barr Faughny,New Zealand,Baker's Choco Chips,2021-01-01,259,22
4,Beverie Moffet,USA,Manuka Honey Choco,2021-01-01,5530,179

In [11]:
sales.isna().sum()

Sales Person    0
Geography       0
Product         0
Date            0
Amount          0
Boxes           0
dtype: int64

In [14]:
sales.loc[[0,1,2]]

,Sales Person,Geography,Product,Date,Amount,Boxes
0,Barr Faughny,New Zealand,Raspberry Choco,2021-01-01,8414,495
1,Dennison Crosswaite,Canada,White Choc,2021-01-01,532,54
2,Karlen McCaffrey,USA,99% Dark & Pure,2021-01-01,5376,269

In [15]:
sales.iloc[[0,2,4]]

,Sales Person,Geography,Product,Date,Amount,Boxes
0,Barr Faughny,New Zealand,Raspberry Choco,2021-01-01,8414,495
2,Karlen McCaffrey,USA,99% Dark & Pure,2021-01-01,5376,269
4,Beverie Moffet,USA,Manuka Honey Choco,2021-01-01,5530,179

In [17]:
sales.loc[[0,2]],['Geography', 'Product']

(       Sales Person      Geography          Product       Date  Amount  Boxes
 0      Barr Faughny    New Zealand  Raspberry Choco 2021-01-01    8414    495
 2  Karlen McCaffrey            USA  99% Dark & Pure 2021-01-01    5376    269,
 ['Geography', 'Product'])

In [18]:
sales.iloc[[0,2,4]],[[0,1,2]]

(       Sales Person      Geography             Product       Date  Amount  \
 0      Barr Faughny    New Zealand     Raspberry Choco 2021-01-01    8414
 2  Karlen McCaffrey            USA     99% Dark & Pure 2021-01-01    5376
 4    Beverie Moffet            USA  Manuka Honey Choco 2021-01-01    5530

    Boxes
 0    495
 2    269
 4    179  ,
 [[0, 1, 2]])

In [20]:
sales.iloc[::]

,Sales Person,Geography,Product,Date,Amount,Boxes
0,Barr Faughny,New Zealand,Raspberry Choco,2021-01-01,8414,495
1,Dennison Crosswaite,Canada,White Choc,2021-01-01,532,54
2,Karlen McCaffrey,USA,99% Dark & Pure,2021-01-01,5376,269
3,Barr Faughny,New Zealand,Baker's Choco Chips,2021-01-01,259,22
4,Beverie Moffet,USA,Manuka Honey Choco,2021-01-01,5530,179
...,...,...,...,...,...,...
3786,Van Tuxwell,India,Drinking Coco,2022-01-19,10682,1526
3787,Rafaelita Blaksland,Australia,Mint Chip Choco,2022-01-18,11746,511
3788,Kelci Walkden,Australia,Spicy Special Slims,2022-01-03,8862,1477
3789,Gunar Cockshoot,New Zealand,Mint Chip Choco,2022-01-21,11592,527
3790,Mallorie Waber,USA,Spicy Special Slims,2022-01-07,3871,431

In [24]:
sales.loc[0:4, 'Geography':'Amount']

       Geography              Product       Date  Amount
0    New Zealand      Raspberry Choco 2021-01-01    8414
1         Canada           White Choc 2021-01-01     532
2            USA      99% Dark & Pure 2021-01-01    5376
3    New Zealand  Baker's Choco Chips 2021-01-01     259
4            USA   Manuka Honey Choco 2021-01-01    5530

In [4]:
import pandas as pd

data = {'Name': ['John', 'Mary', 'Paul'],
        'Age': [25, 30, 22],
        'City': ['Lagos', 'Abuja', 'Ibadan']}
df = pd.DataFrame(data)

In [5]:
df

   Name  Age    City
0  John   25   Lagos
1  Mary   30   Abuja
2  Paul   22  Ibadan

In [11]:
# df.iloc[0]              # Select first row
# df.iloc[:, 1]           # Select second column (Age)
# df.iloc[1, 2]           # Select value at 2nd row, 3rd column -> 'Abuja'
df.iloc[0:2, 0:2]       # Select first 2 rows and first 2 columns

   Name  Age
0  John   25
1  Mary   30

In [17]:
import pandas as pd
import numpy as np

# Data Ingestion

In [18]:
df = pd.read_csv('possum.csv')

# Data Inspection

In [14]:
df.head()

,case,site,Pop,sex,age,hdlngth,skullw,totlngth,taill,footlgth,earconch,eye,chest,belly
0,1,1,Vic,m,8.0,94.1,60.4,89.0,36.0,74.5,54.5,15.2,28.0,36.0
1,2,1,Vic,f,6.0,92.5,57.6,91.5,36.5,72.5,51.2,16.0,28.5,33.0
2,3,1,Vic,f,6.0,94.0,60.0,95.5,39.0,75.4,51.9,15.5,30.0,34.0
3,4,1,Vic,f,6.0,93.2,57.1,92.0,38.0,76.1,52.2,15.2,28.0,34.0
4,5,1,Vic,f,2.0,91.5,56.3,85.5,36.0,71.0,53.2,15.1,28.5,33.0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   case      104 non-null    int64
 1   site      104 non-null    int64
 2   Pop       104 non-null    object
 3   sex       104 non-null    object
 4   age       102 non-null    float64
 5   hdlngth   104 non-null    float64
 6   skullw    104 non-null    float64
 7   totlngth  104 non-null    float64
 8   taill     104 non-null    float64
 9   footlgth  103 non-null    float64
 10  earconch  104 non-null    float64
 11  eye       104 non-null    float64
 12  chest     104 non-null    float64
 13  belly     104 non-null    float64
dtypes: float64(10), int64(2), object(2)
memory usage: 11.5+ KB

In [20]:
df.describe(include='all')

,case,site,Pop,sex,age,hdlngth,skullw,totlngth,taill,footlgth,earconch,eye,chest,belly
count,104.000000,104.000000,104,104,102.000000,104.000000,104.000000,104.000000,104.000000,103.000000,104.000000,104.000000,104.000000,104.000000
unique,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,other,m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,58,61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,52.500000,3.625000,NaN,NaN,3.833333,92.602885,56.883654,87.088462,37.009615,68.459223,48.130769,15.046154,27.000000,32.586538
std,30.166206,2.349086,NaN,NaN,1.909244,3.573349,3.113426,4.310549,1.959518,4.395306,4.109380,1.050374,2.045597,2.761949
min,1.000000,1.000000,NaN,NaN,1.000000,82.500000,50.000000,75.000000,32.000000,60.300000,40.300000,12.800000,22.000000,25.000000
25%,26.750000,1.000000,NaN,NaN,2.250000,90.675000,54.975000,84.000000,35.875000,64.600000,44.800000,14.400000,25.500000,31.000000
50%,52.500000,3.000000,NaN,NaN,3.000000,92.800000,56.350000,88.000000,37.000000,68.000000,46.800000,14.900000,27.000000,32.500000
75%,78.250000,6.000000,NaN,NaN,5.000000,94.725000,58.100000,90.000000,38.000000,72.500000,52.000000,15.725000,28.000000,34.125000
max,104.000000,7.000000,NaN,NaN,9.000000,103.100000,68.600000,96.500000,43.000000,77.900000,56.200000,17.800000,32.000000,40.000000

In [21]:
df.columns

Index(['case', 'site', 'Pop', 'sex', 'age', 'hdlngth', 'skullw', 'totlngth',
       'taill', 'footlgth', 'earconch', 'eye', 'chest', 'belly'],
      dtype='object')

In [22]:
df.dtypes

case          int64
site          int64
Pop          object
sex          object
age         float64
hdlngth     float64
skullw      float64
totlngth    float64
taill       float64
footlgth    float64
earconch    float64
eye         float64
chest       float64
belly       float64
dtype: object

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df.isna().sum()

case        0
site        0
Pop         0
sex         0
age         2
hdlngth     0
skullw      0
totlngth    0
taill       0
footlgth    1
earconch    0
eye         0
chest       0
belly       0
dtype: int64

In [30]:
age_mean = df['age'].mean()

In [ ]:
df['age'] = df['age'].fillna(age_mean)

In [32]:
df.isna().sum()

case        0
site        0
Pop         0
sex         0
age         0
hdlngth     0
skullw      0
totlngth    0
taill       0
footlgth    1
earconch    0
eye         0
chest       0
belly       0
dtype: int64

In [33]:
ft_mean = df['footlgth'].mean()

In [34]:
df['footlgth'] = df['footlgth'].fillna(ft_mean)

In [35]:
df.isna().sum()

case        0
site        0
Pop         0
sex         0
age         0
hdlngth     0
skullw      0
totlngth    0
taill       0
footlgth    0
earconch    0
eye         0
chest       0
belly       0
dtype: int64

# Descriptive statistics

In [36]:
df.describe()

,case,site,age,hdlngth,skullw,totlngth,taill,footlgth,earconch,eye,chest,belly
count,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000
mean,52.500000,3.625000,3.833333,92.602885,56.883654,87.088462,37.009615,68.459223,48.130769,15.046154,27.000000,32.586538
std,30.166206,2.349086,1.890617,3.573349,3.113426,4.310549,1.959518,4.373917,4.109380,1.050374,2.045597,2.761949
min,1.000000,1.000000,1.000000,82.500000,50.000000,75.000000,32.000000,60.300000,40.300000,12.800000,22.000000,25.000000
25%,26.750000,1.000000,2.750000,90.675000,54.975000,84.000000,35.875000,64.650000,44.800000,14.400000,25.500000,31.000000
50%,52.500000,3.000000,3.000000,92.800000,56.350000,88.000000,37.000000,68.100000,46.800000,14.900000,27.000000,32.500000
75%,78.250000,6.000000,5.000000,94.725000,58.100000,90.000000,38.000000,72.500000,52.000000,15.725000,28.000000,34.125000
max,104.000000,7.000000,9.000000,103.100000,68.600000,96.500000,43.000000,77.900000,56.200000,17.800000,32.000000,40.000000

In [38]:
df['age'].mean()

np.float64(3.833333333333333)

In [42]:
num = ['case', 'site', 'age', 'hdlngth', 'skullw', 'totlngth',
       'taill', 'footlgth', 'earconch', 'eye', 'chest', 'belly']

In [47]:
df_num1 = pd.DataFrame({
    'mean': df[num].mean().round(2),
    'median': df[num].median().round(2),
    'mode': df[num].mode().iloc[0].round(2),
    'std': df[num].std().round(2),
    'variance': df[num].var().round(2)
})

In [48]:
df_num1

           mean  median  mode    std  variance
case      52.50   52.50   1.0  30.17    910.00
site       3.62    3.00   1.0   2.35      5.52
age        3.83    3.00   3.0   1.89      3.57
hdlngth   92.60   92.80  93.3   3.57     12.77
skullw    56.88   56.35  57.6   3.11      9.69
totlngth  87.09   88.00  89.0   4.31     18.58
taill     37.01   37.00  38.0   1.96      3.84
footlgth  68.46   68.10  73.2   4.37     19.13
earconch  48.13   46.80  44.9   4.11     16.89
eye       15.05   14.90  14.4   1.05      1.10
chest     27.00   27.00  28.0   2.05      4.18
belly     32.59   32.50  32.0   2.76      7.63

In [49]:
df_num2 = pd.DataFrame({
    'max': df[num].max().round(2),
    'min': df[num].min().round(2),
    'range': (np.subtract(df[num].max(), df[num].min())).round(2),
    '25th_percentile': df[num].quantile(0.25).round(2),
    '50th_percentile': df[num].quantile(0.50).round(2),
    '75th_percentile': df[num].quantile(0.75).round(2),
    'IQR': (np.subtract(df[num].quantile(0.75),df[num].quantile(0.25))).round(2),
    'skewness': df[num].skew(),
    'kurtosis': df[num].kurtosis()
})

In [50]:
df_num2

,max,min,range,25th_percentile,50th_percentile,75th_percentile,IQR,skewness,kurtosis
case,104.0,1.0,103.0,26.75,52.50,78.25,51.50,0.000000,-1.200000
site,7.0,1.0,6.0,1.00,3.00,6.00,5.00,0.187788,-1.584036
age,9.0,1.0,8.0,2.75,3.00,5.00,2.25,0.544263,-0.224131
hdlngth,103.1,82.5,20.6,90.68,92.80,94.72,4.05,-0.055974,0.890902
skullw,68.6,50.0,18.6,54.98,56.35,58.10,3.12,1.007540,2.476359
totlngth,96.5,75.0,21.5,84.00,88.00,90.00,6.00,-0.285266,-0.104531
taill,43.0,32.0,11.0,35.88,37.00,38.00,2.12,0.167869,0.397197
footlgth,77.9,60.3,17.6,64.65,68.10,72.50,7.85,0.092476,-1.179025
earconch,56.2,40.3,15.9,44.80,46.80,52.00,7.20,0.154808,-1.361930
eye,17.8,12.8,5.0,14.40,14.90,15.72,1.32,0.392741,0.054552
chest,32.0,22.0,10.0,25.50,27.00,28.00,2.50,-0.055511,-0.280747
belly,40.0,25.0,15.0,31.00,32.50,34.12,3.12,0.073975,0.172582

In [51]:
df.columns

Index(['case', 'site', 'Pop', 'sex', 'age', 'hdlngth', 'skullw', 'totlngth',
       'taill', 'footlgth', 'earconch', 'eye', 'chest', 'belly'],
      dtype='object')

In [56]:
df.groupby('sex')['age'].agg(
    count= 'count',
    mean= 'mean'
)

     count      mean
sex
f       43  3.976744
m       61  3.732240

In [ ]:
group = df.groupby('sex')['age']
group

sex  age
f    3.000000    11
     2.000000     7
     6.000000     7
     4.000000     6
     5.000000     6
     1.000000     3
     9.000000     2
     7.000000     1
m    3.000000    16
     2.000000     9
     4.000000     8
     1.000000     7
     5.000000     7
     7.000000     6
     6.000000     5
     3.833333     2
     8.000000     1
Name: count, dtype: int64

# Test of hypothesis

Question:
Is the average footlenght of male significantly different from female?

Ho: Mean footleght of a male possum = mean footleght of a female possum
H1: Mean footleght of a male possum != mean footleght of a female possum

In [79]:
male_possum = df["sex"] == "m"
female_possum = df["sex"] == "f"

In [81]:
df.head()

,case,site,Pop,sex,age,hdlngth,skullw,totlngth,taill,footlgth,earconch,eye,chest,belly
0,1,1,Vic,m,8.0,94.1,60.4,89.0,36.0,74.5,54.5,15.2,28.0,36.0
1,2,1,Vic,f,6.0,92.5,57.6,91.5,36.5,72.5,51.2,16.0,28.5,33.0
2,3,1,Vic,f,6.0,94.0,60.0,95.5,39.0,75.4,51.9,15.5,30.0,34.0
3,4,1,Vic,f,6.0,93.2,57.1,92.0,38.0,76.1,52.2,15.2,28.0,34.0
4,5,1,Vic,f,2.0,91.5,56.3,85.5,36.0,71.0,53.2,15.1,28.5,33.0

In [73]:
df['sex'].head()

0    m
1    f
2    f
3    f
4    f
Name: sex, dtype: object

In [82]:
male_df = df[male_possum]
female_df = df[female_possum]

In [92]:
male_mean = male_df['footlgth'].mean()

In [93]:
female_mean = female_df['footlgth'].mean()

In [94]:
from scipy import stats

In [95]:
np.random.seed(42)

In [101]:
female_sample = np.random.normal(loc=female_mean, scale=5, size=30)
male_sample = np.random.normal(loc=male_mean, scale=5, size=30)

In [97]:
female_sample

array([71.58029689, 68.40540462, 72.33516881, 76.71187541, 67.92595925,
       67.92604134, 76.9927902 , 72.93389977, 66.74935419, 71.80952634,
       66.77963766, 66.76807736, 70.30653748, 59.5303249 , 60.47213696,
       66.28528848, 64.03257052, 70.66796279, 64.55660575, 62.03520762,
       76.42496997, 67.96784462, 69.43436715, 61.97298519, 66.3748125 ,
       69.65133907, 63.34175824, 70.97521622, 66.09353267, 67.63825737])

In [102]:
male_sample

array([77.33870862, 70.37900067, 62.05331858, 71.29260411, 63.13642771,
       71.94525908, 73.80281396, 63.90642447, 72.82671671, 70.0737407 ,
       72.12013687, 77.49380098, 66.78289549, 64.24115524, 63.56226392,
       63.93078464, 67.62432752, 69.71559594, 69.39329006, 72.14575231,
       68.07484552, 75.27750645, 66.6865519 , 81.6106819 , 71.1381728 ,
       63.72404828, 62.65537358, 70.42219814, 66.89252214, 71.57983854])

In [103]:
# T-Test
t_stat, p_val = stats.ttest_ind(female_sample, male_sample)

In [104]:
print(f"T-statistics: {t_stat}")

T-statistics: -1.0717541471090717

In [105]:
print(f"P-value: {p_val}")

P-value: 0.2882699086783947