In [2]:
import pandas as pd
import numpy as np

In [ ]:
url = 'https://raw.githubusercontent.com/Meritus3266/Data-files/refs/heads/master/Practice_Newdata/College%20Data.csv'

In [4]:
df = pd.read_csv(url)
df.head()

,College ID,Country,Total Students,Male,Female,CGPA,Annual Family Income,Branch,Sports,Research Papers Published,Placement Rate,Faculty Count
0,College 52,UK,27002,2593,11644,10.000000,3574250,Physics,Swimming,39,100.00,655
1,College 93,Switzerland,11913,9392,2521,6.951278,762556,Chemical Engineering,Athletics,31,68.84,256
2,College 15,Japan,15644,5475,4388,9.327922,1795845,Business Administration,Volleyball,37,91.99,555
3,College 72,Singapore,13239,7363,5876,8.681112,1222223,Physics,Tennis,48,97.98,455
4,College 61,Canada,10236,13339,-3103,8.560567,1921133,Biotechnology,Athletics,34,83.56,310

In [5]:
df.describe()

,Total Students,Male,Female,CGPA,Annual Family Income,Research Papers Published,Placement Rate,Faculty Count
count,50000.000000,50000.000000,50000.000000,50000.000000,5.000000e+04,50000.000000,50000.000000,50000.000000
mean,15522.357440,7747.061900,3555.550780,8.705289,2.611606e+06,24.472300,82.335352,428.919520
std,8366.792001,4188.406336,5892.297104,1.053363,1.387889e+06,14.458858,11.475691,154.733223
min,1001.000000,500.000000,-13917.000000,4.001559,2.000040e+05,0.000000,60.000000,62.000000
25%,8272.750000,4111.000000,527.000000,7.980137,1.408786e+06,12.000000,72.450000,315.000000
50%,15506.500000,7756.000000,3744.000000,8.806043,2.620902e+06,24.000000,82.460000,428.000000
75%,22768.250000,11360.000000,7786.000000,9.652321,3.811208e+06,37.000000,92.470000,544.000000
max,29999.000000,14999.000000,14999.000000,10.000000,4.999988e+06,49.000000,100.000000,796.000000

In [ ]:
df.columns

Index(['College ID', 'Country', 'Total Students', 'Male', 'Female', 'CGPA',
       'Annual Family Income', 'Branch', 'Sports', 'Research Papers Published',
       'Placement Rate', 'Faculty Count'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   College ID                 50000 non-null  object
 1   Country                    50000 non-null  object
 2   Total Students             50000 non-null  int64
 3   Male                       50000 non-null  int64
 4   Female                     50000 non-null  int64
 5   CGPA                       50000 non-null  float64
 6   Annual Family Income       50000 non-null  int64
 7   Branch                     50000 non-null  object
 8   Sports                     50000 non-null  object
 9   Research Papers Published  50000 non-null  int64
 10  Placement Rate             50000 non-null  float64
 11  Faculty Count              50000 non-null  int64
dtypes: float64(2), int64(6), object(4)
memory usage: 4.6+ MB

In [12]:
print(df['Female'].max())

14999