In [1]:
import pandas as pd

In [4]:
df = pd.read_excel('Sales Data.xlsx')
df.head()

,Sales Person,Geography,Product,Date,Amount,Boxes
0,Barr Faughny,New Zealand,Raspberry Choco,2021-01-01,8414,495
1,Dennison Crosswaite,Canada,White Choc,2021-01-01,532,54
2,Karlen McCaffrey,USA,99% Dark & Pure,2021-01-01,5376,269
3,Barr Faughny,New Zealand,Baker's Choco Chips,2021-01-01,259,22
4,Beverie Moffet,USA,Manuka Honey Choco,2021-01-01,5530,179

In [16]:
df.shape
#df.columns

(3791, 6)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3791 entries, 0 to 3790
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sales Person  3791 non-null   object
 1   Geography     3791 non-null   object
 2   Product       3791 non-null   object
 3   Date          3791 non-null   datetime64[ns]
 4   Amount        3791 non-null   int64
 5   Boxes         3791 non-null   int64
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 177.8+ KB

In [26]:
df.describe()

                                Date        Amount        Boxes
count                           3791   3791.000000  3791.000000
mean   2021-07-24 07:40:22.474281472   5724.537589   354.675284
min              2021-01-01 00:00:00      0.000000     0.000000
25%              2021-04-08 00:00:00   2352.000000   120.500000
50%              2021-07-23 00:00:00   4844.000000   265.000000
75%              2021-11-12 00:00:00   8302.000000   480.000000
max              2022-01-31 00:00:00  23268.000000  3075.000000
std                              NaN   4296.484695   335.358698

In [27]:
df.describe(include=object)

       Sales Person Geography          Product
count          3791      3791             3791
unique           26        42               25
top     Brien Boise     India  99% Dark & Pure
freq            160       166              178

In [29]:
df.isna().sum()

Sales Person    0
Geography       0
Product         0
Date            0
Amount          0
Boxes           0
dtype: int64

In [32]:
correlation = df['Amount'].corr(df['Boxes'])
correlation

np.float64(0.8033252774799493)

In [37]:
dup = df.duplicated().sum()
print(f"the no of duplicate in the dataset is {dup}")

the no of duplicate in the dataset is 0